name: Package iLand-Core

on:
  push:
    branches: [ LiteXLoader ]
  pull_request:
    branches: [ LiteXLoader ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: MkDirs
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          mkdir D:/out
          mkdir D:/out/lib
          mkdir D:/out/iland
        
      - name: Copy Dev files
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cp -a iland-core.lua D:/out/
          cp -a iland/* D:/out/iland/
          cp -a install_upgrade_guide.txt D:/out/
        shell: bash
      
      - name: Upload DevPack
        uses: actions/upload-artifact@v1.0.0
        with:
          name: iland-preview
          path: D:/out/
